version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "estadisticas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mox0u3ykh75l"
s3_prefix = "estadisticas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
